from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from market_agent.model import ModelMetrics
from market_agent.models import AnalysisReport


@dataclass(frozen=True)
class AnalysisResult:
    symbol: str
    last_close: float
    last_date: date
    probability_up: float
    signal: str
    rationale: str
    metrics: ModelMetrics
    feature_snapshot: dict[str, float]


def write_report(
    path: Path,
    results: list[AnalysisResult],
    risk_profile: str,
    start: date,
    end: date,
    data_source: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    source_labels = {
        "yfinance": "Yahoo Finance (real historical market data via yfinance)",
        "stooq": "Stooq (real historical market data)",
        "sample": "Synthetic sample data (fictional; offline demonstration only)",
    }
    lines = [
        "# Autonomous Market Analysis Report",
        "",
        f"Requested analysis window: `{start.isoformat()}` to `{end.isoformat()}`",
        f"Data source: **{source_labels.get(data_source, data_source)}**",
        f"Risk profile: `{risk_profile}`",
        "",
        "This report is generated by an educational machine-learning agent and is not financial advice.",
        "",
        "## Signal Summary",
        "",
        "| Symbol | Signal | Last Close | Probability Up | Test Accuracy | Precision | Recall |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]

    for result in sorted(results, key=lambda item: item.probability_up, reverse=True):
        lines.append(
            "| "
            f"{result.symbol} | "
            f"{result.signal} | "
            f"${result.last_close:,.2f} | "
            f"{result.probability_up:.1%} | "
            f"{result.metrics.accuracy:.1%} | "
            f"{result.metrics.precision:.1%} | "
            f"{result.metrics.recall:.1%} |"
        )

    lines.extend(["", "## Ticker Notes", ""])
    for result in sorted(results, key=lambda item: item.symbol):
        lines.extend(
            [
                f"### {result.symbol}",
                "",
                f"- Date: `{result.last_date.isoformat()}`",
                f"- Signal: `{result.signal}`",
                f"- Model probability of next-day upside: `{result.probability_up:.1%}`",
                f"- Rationale: {result.rationale}",
                f"- Test samples: `{result.metrics.samples}`",
                "- Feature snapshot:",
            ]
        )
        for name, value in result.feature_snapshot.items():
            lines.append(f"  - `{name}`: `{value:.4f}`")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def to_json(report: AnalysisReport) -> str:
    return json.dumps(_json_ready(report.to_dict()), indent=2)


def to_markdown(report: AnalysisReport) -> str:
    signals = "\n".join(f"- {signal}" for signal in report.signals)
    return "\n".join(
        [
            f"# Market Analysis: {report.ticker}",
            "",
            f"Generated: `{report.generated_at.isoformat()}`",
            f"Data window: `{report.data_start.isoformat()}` to `{report.data_end.isoformat()}`",
            "",
            "## Snapshot",
            "",
            f"- Last close: `${report.last_close:,.2f}`",
            f"- Period return: `{report.return_period:.1%}`",
            f"- 1-day return: `{report.return_1d:.1%}`",
            f"- Annualized volatility: `{report.volatility_annualized:.1%}`",
            f"- Drawdown from peak: `{report.drawdown_from_peak:.1%}`",
            f"- Trend: `{report.trend}`",
            "",
            "## Prediction",
            "",
            f"- Direction: `{report.prediction.direction}`",
            f"- Probability up: `{report.prediction.probability_up:.1%}`",
            f"- Model: `{report.prediction.model}`",
            f"- Training rows: `{report.prediction.training_rows}`",
            "",
            "## Signals",
            "",
            signals,
            "",
            f"> {report.caveat}",
            "",
        ]
    )


def _json_ready(value: Any) -> Any:
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, dict):
        return {key: _json_ready(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_ready(item) for item in value]
    return value
